# Generated by Django 5.2.8 on 2025-11-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_bid_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='initial_price',
            new_name='initial_bid',
        ),
    ]
