# Generated by Django 5.2.8 on 2025-11-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='price',
        ),
    ]
