# Generated by Django 5.2.8 on 2025-11-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bid_bid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='initial_bid',
            new_name='initial_bid_price',
        ),
    ]
