# Generated by Django 5.2.8 on 2025-11-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_initial_bid_auctionitem_initial_bid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='state',
            field=models.CharField(default='New Listing', max_length=32),
        ),
    ]
